import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Each device has its own sidebar, generated from its folder under `docs/`.
 * To add a new device: create `docs/<device>/`, add a sidebar entry here and
 * register the device in `src/data/devices.ts` (homepage cards + navbar).
 */
const sidebars: SidebarsConfig = {
  olfactometerSidebar: [{type: 'autogenerated', dirName: 'olfactometer'}],
  flypadControllerSidebar: [{type: 'autogenerated', dirName: 'flypad-controller'}],
  currentDriverSidebar: [{type: 'autogenerated', dirName: 'current-driver'}],
};

export default sidebars;
